package nonamecrackers2.witherstormmod.common.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

public class WitherStormModItemTabs {
   public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "witherstormmod");
   public static final DeferredHolder<CreativeModeTab> CREATIVE_TAB = TABS.register(
      "creative_tab",
      () -> CreativeModeTab.builder()
            .icon(() -> new ItemStack((ItemLike)WitherStormModItems.FORMIDIBOMB.get()))
            .title(Component.translatable("itemGroup.wither_storm_mod"))
            .displayItems((flags, output) -> {
               ItemStack phasometer = new ItemStack((ItemLike)WitherStormModItems.PHASOMETER.get());
               CompoundTag phasoNbt = new CompoundTag();
               phasoNbt.putBoolean("IsUpgraded", true);
               phasometer.setTag(phasoNbt);
               ItemStack amulet = new ItemStack((ItemLike)WitherStormModItems.AMULET.get());
               CompoundTag amuletNbt = new CompoundTag();
               amuletNbt.putBoolean("TrackEntityTypes", true);
               amulet.setTag(amuletNbt);
               output.accept((ItemLike)WitherStormModItems.WITHERED_BONE.get());
               output.accept((ItemLike)WitherStormModItems.WITHERED_FLESH.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_DUST.get());
               output.accept((ItemLike)WitherStormModItems.WITHERED_SPIDER_EYE.get());
               output.accept((ItemLike)WitherStormModItems.GOLDEN_APPLE_STEW.get());
               output.accept((ItemLike)WitherStormModItems.WITHERED_NETHER_STAR.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_BOOK.get());
               output.accept((ItemLike)WitherStormModItems.AMULET.get());
               output.accept(amulet);
               output.accept((ItemLike)WitherStormModItems.PHASOMETER.get());
               output.accept(phasometer);
               output.accept((ItemLike)WitherStormModItems.SOURCE_TEST_FIREBALL.get());
               output.accept((ItemLike)WitherStormModItems.WOOD_COMMAND_BLOCK_SWORD.get());
               output.accept((ItemLike)WitherStormModItems.WOOD_COMMAND_BLOCK_PICKAXE.get());
               output.accept((ItemLike)WitherStormModItems.WOOD_COMMAND_BLOCK_AXE.get());
               output.accept((ItemLike)WitherStormModItems.WOOD_COMMAND_BLOCK_SHOVEL.get());
               output.accept((ItemLike)WitherStormModItems.WOOD_COMMAND_BLOCK_HOE.get());
               output.accept((ItemLike)WitherStormModItems.STONE_COMMAND_BLOCK_SWORD.get());
               output.accept((ItemLike)WitherStormModItems.STONE_COMMAND_BLOCK_PICKAXE.get());
               output.accept((ItemLike)WitherStormModItems.STONE_COMMAND_BLOCK_AXE.get());
               output.accept((ItemLike)WitherStormModItems.STONE_COMMAND_BLOCK_SHOVEL.get());
               output.accept((ItemLike)WitherStormModItems.STONE_COMMAND_BLOCK_HOE.get());
               output.accept((ItemLike)WitherStormModItems.IRON_COMMAND_BLOCK_SWORD.get());
               output.accept((ItemLike)WitherStormModItems.IRON_COMMAND_BLOCK_PICKAXE.get());
               output.accept((ItemLike)WitherStormModItems.IRON_COMMAND_BLOCK_AXE.get());
               output.accept((ItemLike)WitherStormModItems.IRON_COMMAND_BLOCK_SHOVEL.get());
               output.accept((ItemLike)WitherStormModItems.IRON_COMMAND_BLOCK_HOE.get());
               output.accept((ItemLike)WitherStormModItems.GOLD_COMMAND_BLOCK_SWORD.get());
               output.accept((ItemLike)WitherStormModItems.GOLD_COMMAND_BLOCK_PICKAXE.get());
               output.accept((ItemLike)WitherStormModItems.GOLD_COMMAND_BLOCK_AXE.get());
               output.accept((ItemLike)WitherStormModItems.GOLD_COMMAND_BLOCK_SHOVEL.get());
               output.accept((ItemLike)WitherStormModItems.GOLD_COMMAND_BLOCK_HOE.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_SWORD.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_PICKAXE.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_AXE.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_SHOVEL.get());
               output.accept((ItemLike)WitherStormModItems.COMMAND_BLOCK_HOE.get());
               output.accept((ItemLike)WitherStormModItems.EYE_OF_THE_STORM.get());
               output.accept((ItemLike)WitherStormModItems.FORMIDI_BLADE.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_BEE_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_CAT_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_CHICKEN_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_COW_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_CREEPER_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_IRON_GOLEM_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_MUSHROOM_COW_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_PARROT_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_PHANTOM_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_PIG_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_PILLAGER_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_SKELETON_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_SNOW_GOLEM_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_SPIDER_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_VILLAGER_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_VINDICATOR_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_WOLF_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.SICKENED_ZOMBIE_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.TENTACLE_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.WITHERED_SYMBIONT_SPAWN_EGG.get());
               output.accept((ItemLike)WitherStormModItems.FIREWORK_BUNDLE.get());
               output.accept((ItemLike)WitherStormModItems.SUPER_TNT.get());
               output.accept((ItemLike)WitherStormModItems.FORMIDIBOMB.get());
               output.accept((ItemLike)WitherStormModItems.SUPER_BEACON.get());
               output.accept((ItemLike)WitherStormModItems.SUPER_SUPPORT_BEACON.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_ZOMBIE_SITTING.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_ZOMBIE_WALL.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_ZOMBIE_LYING.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_BONE_PILE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SKELETON_WALL.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SKULL_CEILING.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_FLESH_VEINS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_FLESH_BLOCK.get());
               output.accept((ItemLike)WitherStormModItems.INFECTED_FLESH_BLOCK.get());
               output.accept((ItemLike)WitherStormModItems.HARDENED_FLESH_BLOCK.get());
               output.accept((ItemLike)WitherStormModItems.WITHERED_PHLEGM_BLOCK.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_DUST_BLOCK.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_DIRT.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STONE_STAIRS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STONE_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STONE_BUTTON.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STONE_PRESSURE_PLATE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_COBBLESTONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_COBBLESTONE_STAIRS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_COBBLESTONE_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_COBBLESTONE_WALL.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SAND.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SANDSTONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SANDSTONE_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SANDSTONE_STAIRS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SANDSTONE_WALL.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_CUT_SANDSTONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_CUT_SANDSTONE_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_CHISELED_SANDSTONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SMOOTH_SANDSTONE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SMOOTH_SANDSTONE_STAIRS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SMOOTH_SANDSTONE_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SMOOTH_SANDSTONE_WALL.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_GLASS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_GLASS_PANE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_LOG.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_WOOD.get());
               output.accept((ItemLike)WitherStormModItems.STRIPPED_TAINTED_LOG.get());
               output.accept((ItemLike)WitherStormModItems.STRIPPED_TAINTED_WOOD.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_PLANKS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_STAIRS.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SLAB.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_FENCE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_FENCE_GATE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_DOOR.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_TRAPDOOR.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_PRESSURE_PLATE.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_BUTTON.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_TORCH.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_SIGN.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_LEAVES.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_MUSHROOM.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_PUMPKIN.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_CARVED_PUMPKIN.get());
               output.accept((ItemLike)WitherStormModItems.TAINTED_JACK_O_LANTERN.get());
            })
            .build()
   );
}
