org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

# Run Gradle itself with Java 21
org.gradle.java.home=C:/Users/Lenovo/.antigravity/extensions/redhat.java-1.52.0-win32-x64/jre/21.0.9-win32-x86_64

# Tell Gradle toolchain where to find Java 17 (for compilation)
org.gradle.java.installations.paths=C:/Users/Lenovo/AppData/Roaming/.minecraft/runtime/java-runtime-gamma-snapshot
